# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false
sudo: required
before_install:
  sudo apt-get install -y gdal-bin
addons:
  apt:
    packages:
    - libnetcdf-dev
    - libgdal-dev
    - libproj-dev
